trigger:
  paths:
    include:
    - packages/landing/*
    - packages/design-system/*
    - packages/design-system-icons/*
    - packages/core/*
    exclude:
    - packages/landing/README.md
  branches:
    include:
    - master
    - homolog
    - dev
pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'bempromotora/clientefinal-landing'
  plataformaclienteapi: $(PLATAFORMA_CLIENTE_API_DEV)
  plataformaclientelanding: $(PLATAFORMA_CLIENTE_LANDING)
  plataformaclienteapp: $(PLATAFORMA_CLIENTE_APP)
  isproduction: true

steps:
- script: |
    echo '##vso[task.setvariable variable=plataformaclienteapi]$(PLATAFORMA_CLIENTE_API_HML)'
    echo '##vso[task.setvariable variable=plataformaclientelanding]$(PLATAFORMA_CLIENTE_LANDING_HML)'
    echo '##vso[task.setvariable variable=plataformaclienteapp]$(PLATAFORMA_CLIENTE_APP_HML)'
  condition: eq(variables['Build.SourceBranchName'], 'homolog')
  displayName: 'Set variables to homolog'

- script: |
    echo '##vso[task.setvariable variable=plataformaclienteapi]$(PLATAFORMA_CLIENTE_API_PROD)'
    echo '##vso[task.setvariable variable=plataformaclientelanding]$(PLATAFORMA_CLIENTE_LANDING_PROD)'
    echo '##vso[task.setvariable variable=plataformaclienteapp]$(PLATAFORMA_CLIENTE_APP_PROD)'
  condition: eq(variables['Build.SourceBranchName'], 'master')
  displayName: 'Set variables to production'

- script: |
    echo NEXT_PUBLIC_PLATAFORMA_CLIENTE_API = $(plataformaclienteapi)
    echo NEXT_PUBLIC_IS_PRODUCTION = $(isproduction)
    echo NEXT_PUBLIC_DOMAIN_COOKIE_BOT_ID = $(REACT_APP_DOMAIN_COOKIE_BOT_ID)
    echo NEXT_PUBLIC_GOOGLE_API_KEY = $(NEXT_PUBLIC_GOOGLE_API_KEY)
    echo PLATAFORMA_CLIENTE_LANDING = $(plataformaclientelanding)
    echo PLATAFORMA_CLIENTE_APP = $(plataformaclienteapp)
  displayName: 'Show variable values'

- task: Docker@2
  displayName: 'Build an image'
  inputs:
    repository: '$(imageName)'
    tags: $(Build.SourceBranchName)
    command: build
    Dockerfile: dockerfile
    arguments: '--build-arg NEXT_PUBLIC_IS_PRODUCTION=$(isproduction)
                --build-arg NEXT_PUBLIC_DOMAIN_COOKIE_BOT_ID=$(REACT_APP_DOMAIN_COOKIE_BOT_ID)
                --build-arg NEXT_PUBLIC_PLATAFORMA_CLIENTE_API=$(plataformaclienteapi)
                --build-arg NEXT_PUBLIC_GOOGLE_API_KEY=$(NEXT_PUBLIC_GOOGLE_API_KEY)
                --build-arg PLATAFORMA_CLIENTE_LANDING=$(plataformaclientelanding)
                --build-arg PLATAFORMA_CLIENTE_APP=$(plataformaclienteapp)'

- task: Docker@2
  displayName: 'Push image'
  inputs:
    containerRegistry: 'DockerHubBem'
    repository: '$(imageName)'
    tags: $(Build.SourceBranchName)
    command: push
