//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dominio.Resource.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anexo {0} não encontrado..
        /// </summary>
        public static string Anexo_IdNaoEncontrado {
            get {
                return ResourceManager.GetString("Anexo_IdNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foram encontrados anexos para o usuario {0}..
        /// </summary>
        public static string Anexo_NaoForamEncontradosAnexosParaUsuario {
            get {
                return ResourceManager.GetString("Anexo_NaoForamEncontradosAnexosParaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de documento ausente ou inválido..
        /// </summary>
        public static string Anexo_TipoDocumentoAusenteOuInvalido {
            get {
                return ResourceManager.GetString("Anexo_TipoDocumentoAusenteOuInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível localizar o tipo de documento..
        /// </summary>
        public static string Anexo_TipoDocumentoNaoLocalizado {
            get {
                return ResourceManager.GetString("Anexo_TipoDocumentoNaoLocalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível localizar o anexo com a Selfie para a biometria..
        /// </summary>
        public static string Anexo_TipoDocumentoSefileBiometriaNaoLocalizado {
            get {
                return ResourceManager.GetString("Anexo_TipoDocumentoSefileBiometriaNaoLocalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum banco encontrado..
        /// </summary>
        public static string Bancario_BancoNaoEncontrado {
            get {
                return ResourceManager.GetString("Bancario_BancoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum tipo de conta encontrado..
        /// </summary>
        public static string Bancario_TipoContaNaoEncontrado {
            get {
                return ResourceManager.GetString("Bancario_TipoContaNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível obter o arquivo do termo de autorização..
        /// </summary>
        public static string Beneficio_NaoFoiPossivelObterArquivoTermoAutorizacao {
            get {
                return ResourceManager.GetString("Beneficio_NaoFoiPossivelObterArquivoTermoAutorizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível obter o termo de consulta de benefício assinado..
        /// </summary>
        public static string Beneficio_NaoFoiPossivelObterTermoAssinado {
            get {
                return ResourceManager.GetString("Beneficio_NaoFoiPossivelObterTermoAssinado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não houve um retorno válido ao anexar o termo de consulta de benefício assinado..
        /// </summary>
        public static string Beneficio_NaoHouveRetornoValidoAoAnexarTermoAssinado {
            get {
                return ResourceManager.GetString("Beneficio_NaoHouveRetornoValidoAoAnexarTermoAssinado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não houve retorno válido de uma nova autorização de consulta do benefício..
        /// </summary>
        public static string Beneficio_NaoHouveRetornoValidoNovaAutorizacaoConsultaBeneficio {
            get {
                return ResourceManager.GetString("Beneficio_NaoHouveRetornoValidoNovaAutorizacaoConsultaBeneficio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não houve um retorno válido do provedor da assinatura do termo de autorização da consulta de benefício INSS..
        /// </summary>
        public static string Beneficio_NaoHouveRetornoValidoProvedorAssinaturaTermoInss {
            get {
                return ResourceManager.GetString("Beneficio_NaoHouveRetornoValidoProvedorAssinaturaTermoInss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro de consulta de benefício não localizada..
        /// </summary>
        public static string Beneficio_RegistroDeConsultaDeBeneficioNaoLocalizada {
            get {
                return ResourceManager.GetString("Beneficio_RegistroDeConsultaDeBeneficioNaoLocalizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro de consulta de benefício não localizado..
        /// </summary>
        public static string Beneficio_RegistroNaoLocalizado {
            get {
                return ResourceManager.GetString("Beneficio_RegistroNaoLocalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O telefone informado deve ser de celular..
        /// </summary>
        public static string Beneficio_TelefoneDeveSerCelular {
            get {
                return ResourceManager.GetString("Beneficio_TelefoneDeveSerCelular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biometria já cadastrada no sistema..
        /// </summary>
        public static string Biometria_JaCadastrada {
            get {
                return ResourceManager.GetString("Biometria_JaCadastrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biometria não encontrada..
        /// </summary>
        public static string Biometria_NaoEncontrada {
            get {
                return ResourceManager.GetString("Biometria_NaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A selfie anexada encontra-se com o status de: {0}..
        /// </summary>
        public static string Biometria_SelfieAuntenticadaSituacao {
            get {
                return ResourceManager.GetString("Biometria_SelfieAuntenticadaSituacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Clube de Beneficios está liberado para clientes com operações ativas com a Bem Promotora, adquira agora mesmo um de nossos produtos e utilize mais esse benefício.&quot;..
        /// </summary>
        public static string Cliente_ClubeBeneficioOperacaoInativa {
            get {
                return ResourceManager.GetString("Cliente_ClubeBeneficioOperacaoInativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado civil não localizado..
        /// </summary>
        public static string Cliente_EstadoCivilNaoEncontrado {
            get {
                return ResourceManager.GetString("Cliente_EstadoCivilNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível localizar o gênero..
        /// </summary>
        public static string Cliente_GeneroNaoEncontrado {
            get {
                return ResourceManager.GetString("Cliente_GeneroNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível localizar o grau de instrução..
        /// </summary>
        public static string Cliente_GrauInstrucaoNaoEncontrado {
            get {
                return ResourceManager.GetString("Cliente_GrauInstrucaoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já houve importação de dados para este cliente..
        /// </summary>
        public static string Cliente_ImportacaoJaRealizada {
            get {
                return ResourceManager.GetString("Cliente_ImportacaoJaRealizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente não encontrado..
        /// </summary>
        public static string Cliente_NaoEncontrado {
            get {
                return ResourceManager.GetString("Cliente_NaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ainda não há registro de que o cliente tenha autorizado a importação de seus dados..
        /// </summary>
        public static string Cliente_NaoHaRegistrodeAutorizacaoParaImportacaoDeDados {
            get {
                return ResourceManager.GetString("Cliente_NaoHaRegistrodeAutorizacaoParaImportacaoDeDados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ inválido..
        /// </summary>
        public static string CNPJ_Invalido {
            get {
                return ResourceManager.GetString("CNPJ_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuração &quot;{0}&quot; inválida ou não localizada..
        /// </summary>
        public static string Configuracao_NaoEncontrada {
            get {
                return ResourceManager.GetString("Configuracao_NaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conjugue não foi encontrado..
        /// </summary>
        public static string Conjugue_NaoEncontrado {
            get {
                return ResourceManager.GetString("Conjugue_NaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você precisa cadastrar os dados do Banco..
        /// </summary>
        public static string ConsultaMargemSiape_CadastroBancoPendente {
            get {
                return ResourceManager.GetString("ConsultaMargemSiape_CadastroBancoPendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta de margem indisponível. Tente novamente..
        /// </summary>
        public static string ConsultaMargemSiape_Indisponivel {
            get {
                return ResourceManager.GetString("ConsultaMargemSiape_Indisponivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possivel excluir esta conta, existem rendimentos vinculados a ela..
        /// </summary>
        public static string Conta_EmUso {
            get {
                return ResourceManager.GetString("Conta_EmUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta não localizada..
        /// </summary>
        public static string Conta_NaoLocalizada {
            get {
                return ResourceManager.GetString("Conta_NaoLocalizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convênio {0} não encontrado..
        /// </summary>
        public static string Convenio_IdNaoEncontrado {
            get {
                return ResourceManager.GetString("Convenio_IdNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum cargo da aeronáutica encontrado..
        /// </summary>
        public static string Convenio_NenhumAeronauticaCargoEncontrado {
            get {
                return ResourceManager.GetString("Convenio_NenhumAeronauticaCargoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum tipo funcional da aeronáutica encontrado..
        /// </summary>
        public static string Convenio_NenhumAeronauticaTipoFuncionalEncontrado {
            get {
                return ResourceManager.GetString("Convenio_NenhumAeronauticaTipoFuncionalEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma espécie de benefício encontrada..
        /// </summary>
        public static string Convenio_NenhumaEspecieBeneficioEncontrada {
            get {
                return ResourceManager.GetString("Convenio_NenhumaEspecieBeneficioEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum convênio encontrado..
        /// </summary>
        public static string Convenio_NenhumEncontrato {
            get {
                return ResourceManager.GetString("Convenio_NenhumEncontrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum cargo da marinha encontrado.
        /// </summary>
        public static string Convenio_NenhumMarinhaCargoEncontrado {
            get {
                return ResourceManager.GetString("Convenio_NenhumMarinhaCargoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum tipo funcional da marinha encontrado..
        /// </summary>
        public static string Convenio_NenhumMarinhaTipoFuncionalEncontrado {
            get {
                return ResourceManager.GetString("Convenio_NenhumMarinhaTipoFuncionalEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum orgão de convênio encontrado..
        /// </summary>
        public static string Convenio_NenhumOrgaoEncontrado {
            get {
                return ResourceManager.GetString("Convenio_NenhumOrgaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum tipo funcional encontrado..
        /// </summary>
        public static string Convenio_NenhumTipoFuncionalEncontrado {
            get {
                return ResourceManager.GetString("Convenio_NenhumTipoFuncionalEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um documento do mesmo tipo vinculado ao cliente..
        /// </summary>
        public static string Documento_JaExisteDeMesmoTipoVinculadoAoCliente {
            get {
                return ResourceManager.GetString("Documento_JaExisteDeMesmoTipoVinculadoAoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O documento não foi localizado..
        /// </summary>
        public static string Documento_NaoLocalizado {
            get {
                return ResourceManager.GetString("Documento_NaoLocalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum orgão emissor encontrado..
        /// </summary>
        public static string Documento_OrgaoEmissorNaoEncontrado {
            get {
                return ResourceManager.GetString("Documento_OrgaoEmissorNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível localizar apenas um órgão emissor com os parêmetros enviados..
        /// </summary>
        public static string Documento_OrgaoEmissorNaoFoiPossivelLocalizarApenasUm {
            get {
                return ResourceManager.GetString("Documento_OrgaoEmissorNaoFoiPossivelLocalizarApenasUm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereco indicado como principal não pode ser removido..
        /// </summary>
        public static string Endereco_IndicadoComoPrincipalNaoPodeSerRemovido {
            get {
                return ResourceManager.GetString("Endereco_IndicadoComoPrincipalNaoPodeSerRemovido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O endereço não foi localizado..
        /// </summary>
        public static string Endereco_NaoEncontrado {
            get {
                return ResourceManager.GetString("Endereco_NaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço principal não localizado..
        /// </summary>
        public static string Endereco_PrincipalNaoLocalizado {
            get {
                return ResourceManager.GetString("Endereco_PrincipalNaoLocalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao criar a proposta..
        /// </summary>
        public static string Error_Proposta {
            get {
                return ResourceManager.GetString("Error_Proposta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houve uma falha ao autenticar o token, tente validar novament.
        /// </summary>
        public static string Falha_auth_token {
            get {
                return ResourceManager.GetString("Falha_auth_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apenas um contrato deve ser informado..
        /// </summary>
        public static string IntencaoOperacao_ApenasUmContratoDeveSerInformado {
            get {
                return ResourceManager.GetString("IntencaoOperacao_ApenasUmContratoDeveSerInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intenção de operação {0} não encontrada.
        /// </summary>
        public static string IntencaoOperacao_IdNaoEncontrada {
            get {
                return ResourceManager.GetString("IntencaoOperacao_IdNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A instituição financeira originadora não permite portabilidade..
        /// </summary>
        public static string IntencaoOperacao_InstituicaoFinanceiraOriginadoraNaoPermitePortabilidade {
            get {
                return ResourceManager.GetString("IntencaoOperacao_InstituicaoFinanceiraOriginadoraNaoPermitePortabilidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intencão de Operação já consta em seu passo final de situação ({0}) para o produto {1} e tipo de operação {2}..
        /// </summary>
        public static string IntencaoOperacao_JaEstaNoPassoFinalDeSituacaoParaProduto {
            get {
                return ResourceManager.GetString("IntencaoOperacao_JaEstaNoPassoFinalDeSituacaoParaProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma intenção de operação encontrada..
        /// </summary>
        public static string IntencaoOperacao_NenhumaEncontrada {
            get {
                return ResourceManager.GetString("IntencaoOperacao_NenhumaEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação de Intenção de Operação atual ({0}) não permite situações extraordinárias..
        /// </summary>
        public static string IntencaoOperacao_SituacaoAtualNaoPermiteSituacaoExtraordinaria {
            get {
                return ResourceManager.GetString("IntencaoOperacao_SituacaoAtualNaoPermiteSituacaoExtraordinaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação atual ({0}) da Intenção de Operação não possui passo de exceção para o produto {1} e tipo de operação: {2}..
        /// </summary>
        public static string IntencaoOperacao_SituacaoAtualSemPassoDeExcecaoParaProduto {
            get {
                return ResourceManager.GetString("IntencaoOperacao_SituacaoAtualSemPassoDeExcecaoParaProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação de Intenção de Operação ({0}) inválida para o produto: {1} e tipo de operação: {2}..
        /// </summary>
        public static string IntencaoOperacao_SituacaoInvalidaParaProduto {
            get {
                return ResourceManager.GetString("IntencaoOperacao_SituacaoInvalidaParaProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação de Intenção de Operação não é excepcional: {0}..
        /// </summary>
        public static string IntencaoOperacao_SituacaoNaoExcepcional {
            get {
                return ResourceManager.GetString("IntencaoOperacao_SituacaoNaoExcepcional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A situação atual da intenção de operação (de #{0}) não permite alteração..
        /// </summary>
        public static string IntencaoOperacao_SituacaoNaoPermiteAlteracao {
            get {
                return ResourceManager.GetString("IntencaoOperacao_SituacaoNaoPermiteAlteracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead {0} não encontrado..
        /// </summary>
        public static string Lead_IdNaoEncontrado {
            get {
                return ResourceManager.GetString("Lead_IdNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nehuma lead encontrada..
        /// </summary>
        public static string Lead_NenhumaEncontrada {
            get {
                return ResourceManager.GetString("Lead_NenhumaEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível localizar apenas um município com os parêmetros enviados..
        /// </summary>
        public static string Localizacao_MunicipioNaoFoipossivelLocalizarApenasUm {
            get {
                return ResourceManager.GetString("Localizacao_MunicipioNaoFoipossivelLocalizarApenasUm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma localização encontrada para tal CEP..
        /// </summary>
        public static string Localizacao_NenhumaEncontradaPeloCep {
            get {
                return ResourceManager.GetString("Localizacao_NenhumaEncontradaPeloCep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma unidade federativa encontrada..
        /// </summary>
        public static string Localizacao_NenhumaUnidadeFederativaEcontrada {
            get {
                return ResourceManager.GetString("Localizacao_NenhumaUnidadeFederativaEcontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum CEP pôde ser localizado com os parâmetros enviados..
        /// </summary>
        public static string Localizacao_NenhumCepLocalizado {
            get {
                return ResourceManager.GetString("Localizacao_NenhumCepLocalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum logradouro encontrado..
        /// </summary>
        public static string Localizacao_NenhumLogradouroEncontrado {
            get {
                return ResourceManager.GetString("Localizacao_NenhumLogradouroEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum município encontrado..
        /// </summary>
        public static string Localizacao_NenhumMunicipioEncontrado {
            get {
                return ResourceManager.GetString("Localizacao_NenhumMunicipioEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível localizar o tipo de logradouro..
        /// </summary>
        public static string Localizacao_TipoLogradouroNaoEncontrado {
            get {
                return ResourceManager.GetString("Localizacao_TipoLogradouroNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login e/ou senha inválidos..
        /// </summary>
        public static string Login_Invalido {
            get {
                return ResourceManager.GetString("Login_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de credencial exigida pelo recurso é diferente do tipo de credencial do usuário..
        /// </summary>
        public static string Login_RecursoTipoCredencialDiferente {
            get {
                return ResourceManager.GetString("Login_RecursoTipoCredencialDiferente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário tenant deve ser informado..
        /// </summary>
        public static string Login_UsuarioTenantDeveSerInformado {
            get {
                return ResourceManager.GetString("Login_UsuarioTenantDeveSerInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Apple Sign In token informado é inválido..
        /// </summary>
        public static string LoginSocial_AppleTokenInformadoInvalido {
            get {
                return ResourceManager.GetString("LoginSocial_AppleTokenInformadoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Facebook token informado é inválido..
        /// </summary>
        public static string LoginSocial_FacebookTokenInformadoInvalido {
            get {
                return ResourceManager.GetString("LoginSocial_FacebookTokenInformadoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Client Id do Google token informado é inválido para a aplicação. Client Id informado: {0}..
        /// </summary>
        public static string LoginSocial_GoogleClientIdInvalido {
            get {
                return ResourceManager.GetString("LoginSocial_GoogleClientIdInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Emitente do Google token informado é inválido. Emitente informado: {0}..
        /// </summary>
        public static string LoginSocial_GoogleEmitenteInvalido {
            get {
                return ResourceManager.GetString("LoginSocial_GoogleEmitenteInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Google token informado está expirado. Data da expiração: {0}..
        /// </summary>
        public static string LoginSocial_GoogleTokenExpirado {
            get {
                return ResourceManager.GetString("LoginSocial_GoogleTokenExpirado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Google token informado é inválido..
        /// </summary>
        public static string LoginSocial_GoogleTokenInformadoInvalido {
            get {
                return ResourceManager.GetString("LoginSocial_GoogleTokenInformadoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Google token informado não possui data de expiração..
        /// </summary>
        public static string LoginSocial_GoogleTokenSemDataExpiracao {
            get {
                return ResourceManager.GetString("LoginSocial_GoogleTokenSemDataExpiracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há implementação que contemple login com a rede social {0}..
        /// </summary>
        public static string LoginSocial_NaoImplementado {
            get {
                return ResourceManager.GetString("LoginSocial_NaoImplementado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token de login social inválido..
        /// </summary>
        public static string LoginSocial_TokenInvalido {
            get {
                return ResourceManager.GetString("LoginSocial_TokenInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loja {0} não encontrada..
        /// </summary>
        public static string Loja_IdNaoEncontrada {
            get {
                return ResourceManager.GetString("Loja_IdNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma loja encontrada..
        /// </summary>
        public static string Loja_NenhumaEncontrada {
            get {
                return ResourceManager.GetString("Loja_NenhumaEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificação não encontrada ({0}).
        /// </summary>
        public static string Notificacao_NaoEncontrada {
            get {
                return ResourceManager.GetString("Notificacao_NaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parâmetro Operação {0} não encontrado..
        /// </summary>
        public static string ParametroOperacao_IdNaoEncontrado {
            get {
                return ResourceManager.GetString("ParametroOperacao_IdNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum Parâmetro de Operação encontrado..
        /// </summary>
        public static string ParametroOperacao_NenhumEcontrado {
            get {
                return ResourceManager.GetString("ParametroOperacao_NenhumEcontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As informações contidas na sua solicitação serão submetidas a analise, sua solicitação está em andamento..
        /// </summary>
        public static string PassosProduto_StatusAnalise {
            get {
                return ResourceManager.GetString("PassosProduto_StatusAnalise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua solicitação foi Aprovada e o valor será creditado..
        /// </summary>
        public static string PassosProduto_StatusAprovada {
            get {
                return ResourceManager.GetString("PassosProduto_StatusAprovada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua solicitação necessita de Assinatura Digital. A assinatura digital é a forma de comprovar sua identidade na internet..
        /// </summary>
        public static string PassosProduto_StatusAssinaturaDigital {
            get {
                return ResourceManager.GetString("PassosProduto_StatusAssinaturaDigital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua solicitação foi Reprovada. Você poderá realizar uma nova solicitação..
        /// </summary>
        public static string PassosProduto_StatusReprovada {
            get {
                return ResourceManager.GetString("PassosProduto_StatusReprovada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os dados informados na solicitação foram recebidos com sucesso e sua solicitação será analisada..
        /// </summary>
        public static string PassosProduto_StatusSolicitacao {
            get {
                return ResourceManager.GetString("PassosProduto_StatusSolicitacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto {0} não encontrado..
        /// </summary>
        public static string Produto_IdNaoEncontrado {
            get {
                return ResourceManager.GetString("Produto_IdNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum produto encontrado..
        /// </summary>
        public static string Produto_NenhumEncontrado {
            get {
                return ResourceManager.GetString("Produto_NenhumEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houve um problema ao autenticar a selfie..
        /// </summary>
        public static string ProvedorUnico_ErroAutenticarSefie {
            get {
                return ResourceManager.GetString("ProvedorUnico_ErroAutenticarSefie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível identificar um rosto na imagem..
        /// </summary>
        public static string ProvedorUnico_SelfieNaoIdentificado {
            get {
                return ResourceManager.GetString("ProvedorUnico_SelfieNaoIdentificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não houve sucesso no retorno do provedor da autenticação..
        /// </summary>
        public static string ProviderAutenticacao_NaoHouveSucessoNoRetornoDoProvedorAutenticacao {
            get {
                return ResourceManager.GetString("ProviderAutenticacao_NaoHouveSucessoNoRetornoDoProvedorAutenticacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não houve sucesso no retorno do provedor de consulta da situação da proposta..
        /// </summary>
        public static string ProviderBemApi_NaoHouveSucessoNoRetornoDoProvedorDeConsultaDaSituacaoDaProposta {
            get {
                return ResourceManager.GetString("ProviderBemApi_NaoHouveSucessoNoRetornoDoProvedorDeConsultaDaSituacaoDaProposta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não houve sucesso no retorno do provedor de busca da lista de benefícios..
        /// </summary>
        public static string ProviderCliente_NaoHouveSucessoNoRetornoDoProvedorListarBeneficios {
            get {
                return ResourceManager.GetString("ProviderCliente_NaoHouveSucessoNoRetornoDoProvedorListarBeneficios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não houve sucesso no retorno do provedor de busca da autorização do beneficiário..
        /// </summary>
        public static string ProviderCliente_NaoHouveSucessoNoRetornoDoProvedorObterAutorizacaoValida {
            get {
                return ResourceManager.GetString("ProviderCliente_NaoHouveSucessoNoRetornoDoProvedorObterAutorizacaoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não houve sucesso no retorno do provedor de obtenção dos dados do cliente..
        /// </summary>
        public static string ProviderCliente_NaoHouveSucessoNoRetornoDoProvedorObterDadosCliente {
            get {
                return ResourceManager.GetString("ProviderCliente_NaoHouveSucessoNoRetornoDoProvedorObterDadosCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não houve sucesso no retorno do provedor de busca da nova autorização do beneficiário..
        /// </summary>
        public static string ProviderCliente_NaoHouveSucessoNoRetornoDoProvedorObterNovaAutorizacao {
            get {
                return ResourceManager.GetString("ProviderCliente_NaoHouveSucessoNoRetornoDoProvedorObterNovaAutorizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não houve sucesso no retorno do provedor da autorização do beneficiário..
        /// </summary>
        public static string ProviderConsignado_NaoHouveSucessoNoRetornoDoProvedorAutorizacaoBeneficiario {
            get {
                return ResourceManager.GetString("ProviderConsignado_NaoHouveSucessoNoRetornoDoProvedorAutorizacaoBeneficiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não houve sucesso no retorno do provedor de consulta de margem SIAPE..
        /// </summary>
        public static string ProviderConsignado_NaoHouveSucessoNoRetornoDoProvedorConsultaMargemSiape {
            get {
                return ResourceManager.GetString("ProviderConsignado_NaoHouveSucessoNoRetornoDoProvedorConsultaMargemSiape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não houve sucesso no retorno do provedor de contratos..
        /// </summary>
        public static string ProviderConsignado_NaoHouveSucessoNoRetornoDoProvedorContratos {
            get {
                return ResourceManager.GetString("ProviderConsignado_NaoHouveSucessoNoRetornoDoProvedorContratos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não houve sucesso no retorno do provedor da simulação..
        /// </summary>
        public static string ProviderConsignado_NaoHouveSucessoNoRetornoDoProvedorSimulacao {
            get {
                return ResourceManager.GetString("ProviderConsignado_NaoHouveSucessoNoRetornoDoProvedorSimulacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não houve sucesso no retorno do provedor de simulação de portabilidade..
        /// </summary>
        public static string ProviderConsignado_NaoHouveSucessoNoRetornoDoProvedorSimulacaoDePortabilidade {
            get {
                return ResourceManager.GetString("ProviderConsignado_NaoHouveSucessoNoRetornoDoProvedorSimulacaoDePortabilidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não houve sucesso no retorno do provedor da simulação de refinanciamento..
        /// </summary>
        public static string ProviderConsignado_NaoHouveSucessoNoRetornoDoProvedorSimulacaoRefinanciamento {
            get {
                return ResourceManager.GetString("ProviderConsignado_NaoHouveSucessoNoRetornoDoProvedorSimulacaoRefinanciamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infelizmente não conseguimos nos contectar com o Clube neste momento, tente novamente em alguns minutos..
        /// </summary>
        public static string ProviderKaledo_NaoHouveSucessoNoRetornoDoProvedorCriarAuntenticarUsuario {
            get {
                return ResourceManager.GetString("ProviderKaledo_NaoHouveSucessoNoRetornoDoProvedorCriarAuntenticarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro na tentativa de obter a geolocalização..
        /// </summary>
        public static string ProviderMaxMind_OcorreuErroAoTentarObterGeolocalizacao {
            get {
                return ResourceManager.GetString("ProviderMaxMind_OcorreuErroAoTentarObterGeolocalizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não houve sucesso no retorno do provedor de assinatura do documento..
        /// </summary>
        public static string ProviderPaperless_NaoHouveSucessoNoRetornoDoProvedorAssinaturaDocumento {
            get {
                return ResourceManager.GetString("ProviderPaperless_NaoHouveSucessoNoRetornoDoProvedorAssinaturaDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não houve sucesso no retorno do provedor de envio de documento para assinatura eletrônica..
        /// </summary>
        public static string ProviderPaperless_NaoHouveSucessoNoRetornoDoProvedorEnviarDocumentoParaAssinatura {
            get {
                return ResourceManager.GetString("ProviderPaperless_NaoHouveSucessoNoRetornoDoProvedorEnviarDocumentoParaAssinatura" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não houve sucesso no retorno do provedor de reenvio do token da assinatura eletrônica..
        /// </summary>
        public static string ProviderPaperless_NaoHouveSucessoNoRetornoDoProvedorReenviarToken {
            get {
                return ResourceManager.GetString("ProviderPaperless_NaoHouveSucessoNoRetornoDoProvedorReenviarToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não houve sucesso no retorno do provedor de autenticação de selfie..
        /// </summary>
        public static string ProviderUnico_NaoHouveSucessoNoRetornoDoProvedorAutenticacaoSelfie {
            get {
                return ResourceManager.GetString("ProviderUnico_NaoHouveSucessoNoRetornoDoProvedorAutenticacaoSelfie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não houve sucesso no retorno do provedor de consulta autenticação de selfie..
        /// </summary>
        public static string ProviderUnico_NaoHouveSucessoNoRetornoDoProvedorConsultaAutenticacaoSelfie {
            get {
                return ResourceManager.GetString("ProviderUnico_NaoHouveSucessoNoRetornoDoProvedorConsultaAutenticacaoSelfie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A obtenção do token de acesso não foi bem sucedida..
        /// </summary>
        public static string ProviderUnico_NaoHouveSucessoNoRetornoDoProvedorObterToken {
            get {
                return ResourceManager.GetString("ProviderUnico_NaoHouveSucessoNoRetornoDoProvedorObterToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendimento com convênio inválido..
        /// </summary>
        public static string Rendimento_ConvenioInvalido {
            get {
                return ResourceManager.GetString("Rendimento_ConvenioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendimento não localizado..
        /// </summary>
        public static string Rendimento_NaoLocalizado {
            get {
                return ResourceManager.GetString("Rendimento_NaoLocalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendimento não localizado para o usuário..
        /// </summary>
        public static string Rendimento_NaoLocalizadoParaUsuario {
            get {
                return ResourceManager.GetString("Rendimento_NaoLocalizadoParaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para o Tipo Funcional servidor, deve ser preenchido o cargo..
        /// </summary>
        public static string Rendimento_TipoAeronautica_CargoNaoInformado {
            get {
                return ResourceManager.GetString("Rendimento_TipoAeronautica_CargoNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendimento do tipo aeronáutica deve ser infomado o tipo funcional..
        /// </summary>
        public static string Rendimento_TipoAeronautica_TipoFuncionalNaoInformado {
            get {
                return ResourceManager.GetString("Rendimento_TipoAeronautica_TipoFuncionalNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendimento de tipo inválido..
        /// </summary>
        public static string Rendimento_TipoInvalido {
            get {
                return ResourceManager.GetString("Rendimento_TipoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para o Tipo Funcional servidor, deve ser preenchido o cargo..
        /// </summary>
        public static string Rendimento_TipoMarinha_CargoNaoInformado {
            get {
                return ResourceManager.GetString("Rendimento_TipoMarinha_CargoNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendimento do tipo marinha deve ser infomado o tipo funcional..
        /// </summary>
        public static string Rendimento_TipoMarinha_TipoFuncionalNaoInformado {
            get {
                return ResourceManager.GetString("Rendimento_TipoMarinha_TipoFuncionalNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma cobertura de seguro encontrada..
        /// </summary>
        public static string SeguroCobertura_Nao_Encontrado {
            get {
                return ResourceManager.GetString("SeguroCobertura_Nao_Encontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum produto de seguro foi encontrado ..
        /// </summary>
        public static string SeguroProdutos_Nao_Encontrado {
            get {
                return ResourceManager.GetString("SeguroProdutos_Nao_Encontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selfie não encontrada..
        /// </summary>
        public static string Selfie_NaoEncontrada {
            get {
                return ResourceManager.GetString("Selfie_NaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simulação não retornou resultados com os parâmetros configurados..
        /// </summary>
        public static string Simulacao_NaoRetornouResultadosComParametrosConfigurados {
            get {
                return ResourceManager.GetString("Simulacao_NaoRetornouResultadosComParametrosConfigurados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simulação não retornou resultados com os parâmetros informados..
        /// </summary>
        public static string Simulacao_NaoRetornouResultadosComParametrosInformados {
            get {
                return ResourceManager.GetString("Simulacao_NaoRetornouResultadosComParametrosInformados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma situação de intenção de operação encontrada..
        /// </summary>
        public static string SituacaoIntencaoOperacao_NenhumaEncontrada {
            get {
                return ResourceManager.GetString("SituacaoIntencaoOperacao_NenhumaEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação já encaminhada para o tipo de documento {0}..
        /// </summary>
        public static string Solicitacao_EmAndamento {
            get {
                return ResourceManager.GetString("Solicitacao_EmAndamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apenas um telefone principal deve ser informado..
        /// </summary>
        public static string Telefone_ApenasUmPrincipalDeveSerInformado {
            get {
                return ResourceManager.GetString("Telefone_ApenasUmPrincipalDeveSerInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi localizado um número de telefone celular..
        /// </summary>
        public static string Telefone_CelularNaolocalizado {
            get {
                return ResourceManager.GetString("Telefone_CelularNaolocalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone indicado como principal não pode ser removido..
        /// </summary>
        public static string Telefone_IndicadoComoPrincipalNaoPodeSerRemovido {
            get {
                return ResourceManager.GetString("Telefone_IndicadoComoPrincipalNaoPodeSerRemovido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone não localizado..
        /// </summary>
        public static string Telefone_NaoLocalizado {
            get {
                return ResourceManager.GetString("Telefone_NaoLocalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ao menos um telefone principal deve ser informado..
        /// </summary>
        public static string Telefone_PrincipalDeveSerInformado {
            get {
                return ResourceManager.GetString("Telefone_PrincipalDeveSerInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguarde {0} segundos para solicitar o reenvio..
        /// </summary>
        public static string TelefoneConfirmacao_AguardeXSegundosParaSolicitarReenvio {
            get {
                return ResourceManager.GetString("TelefoneConfirmacao_AguardeXSegundosParaSolicitarReenvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de confirmação por SMS é aceito somente para telefone celular..
        /// </summary>
        public static string TelefoneConfirmacao_ConfirmacaoPorTelefonemaSomenteParaTelefoneCelular {
            get {
                return ResourceManager.GetString("TelefoneConfirmacao_ConfirmacaoPorTelefonemaSomenteParaTelefoneCelular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foi atingido o limite diário para reenvios do token utilizando esse método..
        /// </summary>
        public static string TelefoneConfirmacao_FoiAtingidoLimiteDiarioReenviosToken {
            get {
                return ResourceManager.GetString("TelefoneConfirmacao_FoiAtingidoLimiteDiarioReenviosToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone já foi confirmado..
        /// </summary>
        public static string TelefoneConfirmacao_JaConfirmado {
            get {
                return ResourceManager.GetString("TelefoneConfirmacao_JaConfirmado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível enviar o token por SMS..
        /// </summary>
        public static string TelefoneConfirmacao_NaoFoiPossivelEnviarTokenPorSms {
            get {
                return ResourceManager.GetString("TelefoneConfirmacao_NaoFoiPossivelEnviarTokenPorSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível enviar o token por Torpedo de Voz..
        /// </summary>
        public static string TelefoneConfirmacao_NaoFoiPossivelEnviarTokenPorTorpedoVoz {
            get {
                return ResourceManager.GetString("TelefoneConfirmacao_NaoFoiPossivelEnviarTokenPorTorpedoVoz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível enviar o token por Whatsapp..
        /// </summary>
        public static string TelefoneConfirmacao_NaoFoiPossivelEnviarTokenPorWhatsapp {
            get {
                return ResourceManager.GetString("TelefoneConfirmacao_NaoFoiPossivelEnviarTokenPorWhatsapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token inválido..
        /// </summary>
        public static string TelefoneConfirmacao_TokenInvalido {
            get {
                return ResourceManager.GetString("TelefoneConfirmacao_TokenInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propriedade inexistente em {0}: {1}..
        /// </summary>
        public static string TemplateBuilder_PropriedadeInexistente {
            get {
                return ResourceManager.GetString("TemplateBuilder_PropriedadeInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template de e-mail ausente: {0}..
        /// </summary>
        public static string TemplateEmail_Ausente {
            get {
                return ResourceManager.GetString("TemplateEmail_Ausente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template de notificação ausente: {0}..
        /// </summary>
        public static string TemplateNotificacao_Ausente {
            get {
                return ResourceManager.GetString("TemplateNotificacao_Ausente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de operação {0} não encontrado..
        /// </summary>
        public static string TipoOperacao_IdNaoEncontrado {
            get {
                return ResourceManager.GetString("TipoOperacao_IdNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum tipo de operação encontrado..
        /// </summary>
        public static string TipoOperacao_NenhumEncontrado {
            get {
                return ResourceManager.GetString("TipoOperacao_NenhumEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de solicitação de confirmação não implementado..
        /// </summary>
        public static string TipoSolicitacaoConfirmacao_NaoImplementado {
            get {
                return ResourceManager.GetString("TipoSolicitacaoConfirmacao_NaoImplementado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum vinculo encontrado..
        /// </summary>
        public static string TipoVinculoInstitucional_NenhumEncontrado {
            get {
                return ResourceManager.GetString("TipoVinculoInstitucional_NenhumEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu e-mail já está confirmado..
        /// </summary>
        public static string Usario_EmailConfirmado {
            get {
                return ResourceManager.GetString("Usario_EmailConfirmado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ainda não confirmado. Enviamos um link para a confirmação no seu email..
        /// </summary>
        public static string Usario_EmailNaoConfirmado {
            get {
                return ResourceManager.GetString("Usario_EmailNaoConfirmado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser informado e-mail ou o CPF..
        /// </summary>
        public static string Usuario_DeveInformarEmailOuCpf {
            get {
                return ResourceManager.GetString("Usuario_DeveInformarEmailOuCpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este e-mail não foi encontrado..
        /// </summary>
        public static string Usuario_EmailNaoEncontrado {
            get {
                return ResourceManager.GetString("Usuario_EmailNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível enviar o email de boas vindas para o usuário id: {0}..
        /// </summary>
        public static string Usuario_erroEnvioEmail {
            get {
                return ResourceManager.GetString("Usuario_erroEnvioEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário já cadastrado no sistema..
        /// </summary>
        public static string Usuario_JaCadastrado {
            get {
                return ResourceManager.GetString("Usuario_JaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado..
        /// </summary>
        public static string Usuario_NaoEncontrado {
            get {
                return ResourceManager.GetString("Usuario_NaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houve um problema ao enviar o e-mail de recuperação de senha..
        /// </summary>
        public static string Usuario_ProblemaEmailRecuperacaoSenha {
            get {
                return ResourceManager.GetString("Usuario_ProblemaEmailRecuperacaoSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário ainda não criou uma proposta..
        /// </summary>
        public static string Usuario_Sem_Proposta {
            get {
                return ResourceManager.GetString("Usuario_Sem_Proposta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha atual informada não confere com a do usuário..
        /// </summary>
        public static string Usuario_SenhaAtualNaoConfereComUsuario {
            get {
                return ResourceManager.GetString("Usuario_SenhaAtualNaoConfereComUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token expirado..
        /// </summary>
        public static string Usuario_TokenExpirado {
            get {
                return ResourceManager.GetString("Usuario_TokenExpirado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token inválido..
        /// </summary>
        public static string Usuario_TokenInvalido {
            get {
                return ResourceManager.GetString("Usuario_TokenInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário logado é diferente do usuário de origem do registro..
        /// </summary>
        public static string Usuario_UsuarioLogadoDiferenteDoUsuarioOrigem {
            get {
                return ResourceManager.GetString("Usuario_UsuarioLogadoDiferenteDoUsuarioOrigem", resourceCulture);
            }
        }
    }
}
